"""init

Revision ID: 408e87e1f500
Revises: 
Create Date: 2025-10-27 10:47:44.334934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '408e87e1f500'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    op.create_unique_constraint(None, 'product_categories', ['uid'])
    op.add_column('products', sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint(None, 'products', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'image_urls')
    op.drop_constraint(None, 'product_categories', type_='unique')
    op.create_table('product_images',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_uid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('main_image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_uid'], ['products.uid'], name=op.f('product_images_product_uid_fkey')),
    sa.PrimaryKeyConstraint('uid', name=op.f('product_images_pkey'))
    )
    # ### end Alembic commands ###
